# image: registry.gitlab.com/pages/hugo:latest
# image: cibuilds/hugo <-- includes hugo extended functionality.
# v--- does too, but is 1/5th of the size.
image: dettmering/hugo-build


variables:
  GIT_SUBMODULE_STRATEGY: recursive


build:
  script:
  - hugo --gc --minify
  artifacts:
    paths:
    - public
  only:
  - master
  stage: build


pages:
  artifacts:
    paths:
    - public
  only:
  - master
  stage: deploy
