variables:
  GIT_SUBMODULE_STRATEGY: recursive


build:
  # All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
  # image: registry.gitlab.com/pages/hugo:latest
  image: cibuilds/hugo
  before_script:
  # - snap refresh hugo --channel=extended
  # - snap install hugo --channel=extended
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  stage: build


deploy:
  image: node:4.2.2
  cache:
    paths:
    - node_modules
  before_script:
  - npm install -g firebase-tools
  script:
  - firebase use default --token $FIREBASE_DEPLOY_KEY
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive
  only:
  - master
  stage: deploy
