version: 2.1


jobs:
  build_and_deploy_to_gh_pages:
    docker:
    - image: cibuilds/hugo:latest
    environment:
      HUGO_ENV: production
    steps:
    - checkout
    - add_ssh_keys:
        fingerprint: 60:61:5b:d0:03:dc:d6:61:9f:ff:4a:83:6b:5e:c1:6f
    - run: git config --global user.name "Paul Koppen"
    - run: git config --global user.email "p.koppen@surrey.ac.uk"
    - run:
        name: Build the web pages.
        command: hugo --gc --minify -d /tmp/public
    - run: ls -la /tmp/public
    - run: git checkout gh-pages
    - run: git clean -df .
    - run: git rm -rf *
    - run: mv /tmp/public/* .
    - run: git commit -am "Automated website build."
    - run: git push


workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_deploy_to_gh_pages:
        filters:
          branches:
            only: master
