version: 2.1


jobs:
  build_and_deploy_to_gh_pages:
    docker:
    - image: cibuilds/hugo:latest
    environment:
      HUGO_ENV: production
    steps:
    - add_ssh_keys:
        fingerprint: dd:d9:48:de:fd:a8:82:5e:d2:ba:9e:95:00:1a:1f:1e
    - run: git config --global user.name "Paul Koppen"
    - run: git config --global user.email "p.koppen@surrey.ac.uk"
    - checkout
    - run:
        name: Build the web pages.
        command: hugo --gc --minify -d /tmp/public
    - run: git checkout gh-pages
    - run: git clean -df .
    - run: git rm -rf *
    - run: mv /tmp/public/* .
    - run: git commit -am "Automated website build."
    - run: git push


workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build_and_deploy_to_gh_pages:
        filters:
          branches:
            only: master
