# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "The Wumpus Theme"
license = "MIT"
licenselink = "https://github.com/cvssp/gohugo-theme-wumpus/blob/master/LICENSE.md"
description = "A nice theme, visually inspired by Attila for ghost."
homepage = "https://github.com/cvssp/gohugo-theme-wumpus"
tags = ["website", "starter", "responsive", "Disqus", "blog"]
features = ["posts", "shortcodes", "related content", "comments", "members"]
min_version = 0.30.2
